### ISSUE TITLE
Search: give error page

### ISSUE THREAD

**Issue by hathix** [nickboucher/nova#4]
On the [search page](http://nova.ga/search), if you search for a club or event that doesn't exist, you see nothing: 

![screen shot 2017-01-14 at 11 54 00 am](https://cloud.githubusercontent.com/assets/728084/21956489/265e176a-da50-11e6-9bf5-01fdc2ec1af3.png)

To ensure users don't get confused, consider having an error message like "No club or project matches this description" if nothing is found.

**Comment by nickboucher** [comment]
This is modeled after the Twitter Typeahead system (https://twitter.github.io/typeahead.js/), which is the most-current standard in instant search boxes. Following the style of this standard, I will opt to keep without an error message (it would be too confusing to see an error message when typing, which is the only option since it is an instant-search typeahead). 

Will reopen issue if receiving negative UI feedback from users.
