### ISSUE TITLE
Make it easier to find a grant's status page

### ISSUE THREAD

**Issue by hathix** [nickboucher/nova#5]
Currently, you can only see the grant status page from the search page. But on the Interviews and Small Grants page, when you see a row for a grant, there's no way to get to the status page:

![screen shot 2017-01-14 at 11 55 25 am](https://cloud.githubusercontent.com/assets/728084/21956495/5a9d5e14-da50-11e6-9645-d8050114f40b.png)

It looks like the row is already crowded, but consider adding a link to the grant's status page. Consistency across different parts of the UI really helps reduce user confusion.

**Comment by nickboucher** [comment]
This was a purposeful decision -- the status page should not be viewed by the interviewer during the interview process. The status page is really only for applicants monitoring their grant's status, and the search page is (at the time) just so that we can check where a grant is in the process *after* it has been interviewed
